import { technologyTypeOptionsData, provincesOptions } from './api/const';
import { chonseTypeEquip, displayProcess } from './drainageUtil';
import { EQUIP } from './equipUtil';
import { FormSchema } from '/@/components/Table';

export const formSchemaDrainage: FormSchema[] = [
  {
    field: 'projectID',
    label: '项目ID',
    component: 'InputNumberExpand1',
    show: false,
    dynamicDisabled: true,
    colProps: { span: EQUIP.WIDTH_NUMBER },
  },
  {
    field: 'stationID',
    label: '车站ID',
    component: 'InputNumberExpand1',
    dynamicDisabled: true,
    show: false,
    colProps: { span: EQUIP.WIDTH_NUMBER },
  },

  {
    field: 'divider-linked',
    component: 'Divider',
    label: '请选择最终出路',
    colProps: {
      span: 24,
    },
  },
  {
    field: 'outType',
    component: 'Select',
    label: '最终出路',
    required: true,
    colProps: {
      span: EQUIP.WIDTH_NUMBER,
    },
    componentProps: ({ formModel, formActionType }) => {
      return {
        options: provincesOptions,
        placeholder: '请选择',
        onChange: (e: any) => {
          let technologyTypeOptions = technologyTypeOptionsData[e];
          const { updateSchema } = formActionType;
          let mes = '请选择';
          if (e === undefined) {
            technologyTypeOptions = [];
            mes = '请先选择《最终出路》';
          }
          formModel.technologyType = undefined;
          chonseTypeEquip('', updateSchema);
          displayProcess('', updateSchema);
          updateSchema({
            field: 'technologyType',
            componentProps: () => {
              return {
                options: technologyTypeOptions,
                placeholder: mes,
                onChange: (e: any) => {
                  displayProcess(e, updateSchema);
                  chonseTypeEquip(e, updateSchema);
                },
              };
            },
          });
        },
      };
    },
  },
  {
    field: 'technologyType',
    component: 'Select',
    label: '处理工艺',
    required: true,
    colProps: {
      span: EQUIP.WIDTH_NUMBER,
    },
    componentProps: () => {
      return {
        options: [],
        placeholder: '请先选择《最终出路》',
      };
    },
  },
  {
    label:
      '处理流程:进水→2调节泵井及泵组→1SBR设备→4抽升泵井及泵组→3过滤器→5回用水池、泵组及消毒→回用',
    field: 'divider101',
    component: 'Divider',
    show: false,
    colProps: {
      span: 22,
    },
  },

  {
    label: '污水调节泵井及泵组选型',
    field: 'divider20',
    component: 'Divider',
  },
  {
    label: '◆ 污水调节泵井计算',
    field: 'divider21',
    component: 'Divider',
    colProps: { span: 23 },
  },
  {
    field: 'sewageRegulatingWellVolume',
    label: '泵井有效容积',
    helpMessage: '污水调节泵井有效容积V1（m3），按停留时间6h计。',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: true,
  },

  {
    field: 'adjustWellDiameter',
    label: '泵井直径',
    helpMessage: '污水调节泵井直径D1（m），院通用图“肆水（2017）7411”。',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: false,
  },
  {
    field: 'adjustWellWaterDepth',
    label: '泵井有效水深',
    helpMessage: '污水调节泵井有效水深（m）',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: true,
  },
  {
    field: 'adjustWellWaterPipeElevation',
    label: '进水管底标高',
    helpMessage: '污水调节泵井进水管底绝对标高（m）',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: false,
  },
  {
    field: 'adjustWellStopPumpWaterLevel',
    label: '停泵水位',
    helpMessage: '开泵水位在进水管底以下0.2m',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: true,
  },
  {
    field: 'sbrDesignGroundElevationPumpWell',
    label: '泵井设计地面标高',
    helpMessage: '调节井设计地面标高h17（m）。',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: false,
  },
  {
    field: 'sbrStopPumpWaterLevelInnerHeight',
    label: '停泵水位距内底高',
    helpMessage: '按水泵参数选取，需考虑水泵基础高度0.3m,h18',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: false,
  },
  {
    field: 'sbrconcreteThickness',
    label: '调节井封底混凝土厚度h19（m）',
    helpMessage: '',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    show: false,
    dynamicDisabled: false,
  },
  {
    field: 'adjustWellDepth',
    label: '泵井高度',
    helpMessage: '污水调节泵井深度H（m），院通用图“肆水（2017）7411”。按H≥h17+0.3-h3+h18+h19计。',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: true,
  },
  {
    label: '◆ 潜污泵组计算',
    field: 'divider22',
    component: 'Divider',
    colProps: { span: 23 },
  },
  {
    field: 'adjustWellPumpFlow',
    label: '潜污泵流量',
    helpMessage: '调节泵井内潜污泵流量(m3/h），按处理设备一周期6h，进水时间为1.5h计。',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: true,
  },
  {
    field: 'sbrDeviceInletPipeElevation',
    label: '设备进管标高',
    helpMessage: '处理设备进水管绝对标高（m）',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: false,
  },
  {
    field: 'adjustWellTotalHeadLoss',
    label: '总水头损失',
    helpMessage: '',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER_JS },
    dynamicDisabled: false,
  },
  {
    field: 'js1',
    component: 'Input',
    label: '',
    colProps: { span: 1 },
    slot: 'add1',
  },
  {
    field: 'sewageTreatmentOutflowHead',
    label: '流出水头',
    helpMessage: '处理设备进水管流出水头h6（m），推荐取2~3。',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    defaultValue: 2,
    dynamicDisabled: false,
  },
  {
    field: 'adjustWellPumpLift',
    label: '潜污泵扬程',
    helpMessage: '调节泵井内潜污泵扬程H1（m）。',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: true,
  },
  {
    field: 'adjustPumpModel',
    label: '污水调节泵井及泵组选型',
    dynamicDisabled: true,
    colProps: { span: EQUIP.WIDTH_TEXT_AREA },
    component: 'InputTextArea',
    labelWidth: EQUIP.WIDTH_LABEL_WIDTH,
  },
  {
    label: 'SBR设备选型',
    field: 'divider10',
    component: 'Divider',
  },
  {
    field: 'sewageTreatmentCapacity',
    label: '处理污水量',
    helpMessage: '需处理的污水量(m3/d）',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },

    dynamicDisabled: false,
  },
  {
    field: 'sbrDeviceWork',
    label: '设备工作班数',
    helpMessage: 'SBR（间歇式）设备工作班数，默认为3班制。',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    // defaultValue: 3,

    dynamicDisabled: false,
  },
  {
    field: 'sbrCycleWorkTime',
    label: '处理周期时长',
    helpMessage: 'SBR（间歇式）设备每周期工作时间（h），默认为6h。',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    // defaultValue: 6,

    dynamicDisabled: false,
  },
  {
    field: 'sbrDeviceSpecs',
    label: '设备处理能力',
    helpMessage: 'SBR（间歇式）设备需达到的处理规模Q1(m3/h）',
    component: 'InputNumberExpand3',
    colProps: { span: EQUIP.WIDTH_NUMBER },

    dynamicDisabled: true,
  },
  {
    field: 'sbrModel',
    label: 'SBR设备选型',
    dynamicDisabled: true,
    colProps: { span: EQUIP.WIDTH_TEXT_AREA },
    component: 'InputTextArea',
    labelWidth: EQUIP.WIDTH_LABEL_WIDTH,
  },
  {
    label: '污水调节井及泵组选型',
    field: 'divider70',
    component: 'Divider',
  },
  {
    label: '◆ 污水调节泵井计算',
    field: 'divider71',
    component: 'Divider',
    colProps: { span: 23 },
  },

  {
    field: 'adjustTime',
    label: '调蓄时间',
    helpMessage: '调节泵井调蓄时间t（h），MBR设备推荐采用4~6h；污水量大时取小值。',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: false,
  },
  {
    field: 'mbrSewageRegulatingWellVolume',
    label: '泵井有效容积',
    helpMessage: '污水调节泵井有效容积V（m3），按停留时间4~6h计。',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: true,
  },
  {
    field: 'mbrAdjustWellDiameter',
    label: '泵井直径',
    helpMessage: '污水调节泵井直径D，院通用图“肆水（2017）7411”。',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: false,
  },
  {
    field: 'mbrAdjustWellWaterDepth',
    label: '泵井有效水深',
    helpMessage: '污水调节泵井有效水深（m），按V/（3.14*(D1/2)^2）≤h1≤2.0m计。',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: true,
  },
  {
    field: 'mbrAdjustWellWaterPipeElevation',
    label: '进水管底标高',
    helpMessage: '污水调节泵井进水管底绝对标高（m）',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: false,
  },
  {
    field: 'mbrAdjustWellStopPumpWaterLevel',
    label: '停泵水位',
    helpMessage: '开泵水位在进水管底以下0.2m',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: true,
  },
  {
    field: 'mbrDesignGroundElevationPumpWell',
    label: '泵井设计地面标高',
    helpMessage: '抽升泵井设计地面标高h7（m）。',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: false,
  },
  {
    field: 'mbrStopPumpWaterLevelInnerHeight',
    label: '停泵水位距内底高',
    helpMessage: '按水泵参数选取，需考虑水泵基础高度0.3m，h8',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: false,
  },
  {
    field: 'mbrconcreteThickness',
    label: '调节井封底混凝土厚度h9（m）',
    helpMessage: '',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    show: false,
    dynamicDisabled: false,
  },
  {
    field: 'mbrLiftWellHeight',
    label: '泵井高度',
    helpMessage: '污水调节泵井深度H（m），院通用图“肆水（2017）7411”。按H1≥h7+0.3-h3+h8+h9计。',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: true,
  },

  {
    label: '◆ 潜污泵组计算',
    field: 'divider72',
    component: 'Divider',
    colProps: { span: 23 },
  },

  {
    field: 'mbrAdjustWellPumpFlow',
    label: '潜污泵流量',
    helpMessage: '调节泵井内潜污泵流量(m3/h），按处理设备进水流量计。',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: true,
  },
  {
    field: 'mbrDeviceInletPipeElevation',
    label: '设备进管标高',
    helpMessage: '处理设备进水管绝对标高（m），h4。',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: false,
  },
  {
    field: 'mbrTotalHeadLoss',
    label: '总水头损失',
    helpMessage: '',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER_JS },
    dynamicDisabled: false,
  },
  {
    field: 'js4',
    component: 'Input',
    label: '',
    colProps: { span: 1 },
    slot: 'add4',
  },
  {
    field: 'mbrDeviceOutflowHead',
    label: '流出水头',
    helpMessage: '处理设备进水管流出水头h6（m），推荐取2~3。',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: false,
  },
  {
    field: 'mbrPumpLift',
    label: '潜污泵扬程',
    helpMessage: '调节泵井内潜污泵扬程（m）。',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: true,
  },
  {
    field: 'adjustWellModel',
    label: '污水调节泵井及泵组选型',
    dynamicDisabled: true,
    colProps: { span: EQUIP.WIDTH_TEXT_AREA },
    component: 'InputTextArea',
    labelWidth: EQUIP.WIDTH_LABEL_WIDTH,
  },
  //6
  {
    label: 'MBR设备选型',
    field: 'divider60',
    component: 'Divider',
  },

  {
    field: 'mbrSewageTreatmentCapacity',
    label: '处理污水量',
    helpMessage: '需处理的污水量(m3/d）',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: false,
  },
  {
    field: 'mbrDeviceSpecs',
    label: '设备处理能力',
    helpMessage: 'MBR设备需达到的处理规模Q1(m3/h），按Q1≥W/24计。',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: true,
  },
  {
    field: 'mbrModel',
    label: 'MBR设备选型',
    dynamicDisabled: true,
    colProps: { span: EQUIP.WIDTH_TEXT_AREA },
    component: 'InputTextArea',
    labelWidth: EQUIP.WIDTH_LABEL_WIDTH,
  },
  //4
  {
    label: '污水抽升泵井及泵组选型',
    field: 'divider40',
    component: 'Divider',
  },
  {
    label: '◆ 污水抽升泵井计算',
    field: 'divider41',
    component: 'Divider',
    colProps: { span: 23 },
  },

  {
    field: 'pumpingWellDiameter',
    label: '泵井直径',
    helpMessage: '污水抽升泵井直径D2（m），院通用图“肆水（2017）7411”。',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: false,
  },
  {
    field: 'sewageStopTime',
    label: '停留时间',
    helpMessage: '污水停留时间t（h），推荐取0.5~1h',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: false,
  },
  {
    field: 'pumpingWellVolume',
    label: '泵井有效容积',
    helpMessage: '污水抽升泵井有效容积V2（m3），按停留时间0.5~1h计。',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: true,
  },
  {
    field: 'pumpingWellWaterDepth',
    label: '泵井有效水深',
    helpMessage: '污水抽升泵井有效水深（m），按V2/（3.14*(D2/2)^2）≤h7计。',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: true,
  },

  {
    field: 'pumpingWellWaterPipeElevation',
    label: '进水管底标高',
    helpMessage: '污水抽升泵井进水管底绝对标高（m）',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: false,
  },
  {
    field: 'pumpingWellStopPumpWaterLevel',
    label: '停泵水位',
    helpMessage: '开泵水位在进水管底以下0.2m',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: true,
  },
  {
    field: 'pwDesignGroundElevationPumpWell',
    label: '泵井设计地面标高',
    helpMessage: '抽升井设计地面标高h20（m）。',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: false,
  },
  {
    field: 'pwStopPumpWaterLevelInnerHeight',
    label: '停泵水位距内底高',
    helpMessage: '按水泵参数选取，需考虑水泵基础高度0.3m，h21',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: false,
  },
  {
    field: 'pwconcreteThickness',
    label: '调节井封底混凝土厚度h19（m）',
    helpMessage: '',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    show: false,
    dynamicDisabled: false,
  },
  {
    field: 'pwLiftWellHeight',
    label: '泵井高度',
    helpMessage: '污水调节泵井深度H（m），院通用图“肆水（2017）7411”。按H≥h20+0.3-h9+h21+h22计。',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: true,
  },
  //WC
  {
    label: '◆ 潜污泵组计算',
    field: 'divider42',
    component: 'Divider',
    colProps: { span: 23 },
  },
  {
    field: 'pumpingWellPumpFlow',
    label: '潜污泵流量',
    helpMessage: '抽升泵井内潜污泵流量(m3/h），按处理设备出水流量计。',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: true,
  },
  {
    field: 'filterWaterInletPressure',
    label: '过滤器进水压力',
    helpMessage: '过滤器进水压力（m水头），默认为5m。',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: false,
  },
  {
    field: 'pumpingWellTotalHeadLoss',
    label: '总水头损失',
    helpMessage: '',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER_JS },
    dynamicDisabled: false,
  },
  {
    field: 'js2',
    component: 'Input',
    label: '',
    colProps: { span: 1 },
    slot: 'add2',
  },
  {
    field: 'filterWaterInletElevation',
    label: '过滤器进管管标高',
    helpMessage: '过滤器进水管标高（m）',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: false,
  },
  {
    field: 'sewageExcessHead',
    label: '富裕水头',
    helpMessage: '抽升泵井出水管流出水头h12（m），推荐取2~3。',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: false,
  },
  {
    field: 'pumpingWellPumpLift',
    label: '潜污泵扬程',
    helpMessage: '抽升泵井潜污泵扬程H2（m）。',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: true,
  },
  {
    field: 'pumpingWellModel',
    label: '污水抽升泵井及泵组选型',
    dynamicDisabled: true,
    colProps: { span: EQUIP.WIDTH_TEXT_AREA },
    component: 'InputTextArea',
    labelWidth: EQUIP.WIDTH_LABEL_WIDTH,
  },
  //3
  {
    label: '过滤器选型',
    field: 'divider30',
    component: 'Divider',
  },
  {
    field: 'filterSpecs',
    label: '过滤器规格',
    helpMessage: '过滤器规格Q4(m3/h），按污水抽升井潜污泵流量Q3计。',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: true,
  },
  {
    label: '回用水池、泵组及消毒设备选型',
    field: 'divider50',
    component: 'Divider',
  },
  {
    label: '◆ 回用水池计算',
    field: 'divider51',
    component: 'Divider',
    colProps: { span: 23 },
  },

  {
    field: 'makeGreenSprinklingWater',
    label: '绿化浇洒用水量',
    helpMessage: '每日绿化及浇洒用水量(m3/d），根据道路及绿化面积确定，详用水量计算',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: false,
  },
  {
    field: 'reuseWaterTankVolume',
    label: '水池有效容积',
    helpMessage: '回用水池（箱）或回用井有效容积（m3），按每日浇洒2次储存',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: true,
  },
  {
    label: '◆ 回用泵组计算',
    field: 'divider52',
    component: 'Divider',
    colProps: { span: 23 },
  },

  {
    field: 'sprinklerFlowRate',
    label: '洒水栓流量',
    helpMessage: '单个洒水栓流量(L/s）：DN20水栓为0.4L/s，DN25为0.7L/s',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: false,
  },
  {
    field: 'reusePumpFlow',
    label: '回用泵流量',
    helpMessage: '回用泵流量Q5(m3/h），按同时开启4个栓计。',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: false,
  },
  {
    field: 'makeGreenTotalHeadLoss',
    label: '总水头损失',
    helpMessage: '',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER_JS },
    dynamicDisabled: false,
  },
  {
    field: 'js3',
    component: 'Input',
    label: '',
    colProps: { span: 1 },
    slot: 'add3',
  },
  {
    field: 'sprinklerWorkPressure',
    label: '洒水栓工作压力',
    helpMessage: '洒水栓工作压力（m水头)，默认为10m。',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: false,
  },
  {
    field: 'dullSprinklerGroundLevel',
    label: '洒水栓地面标高',
    helpMessage: '最不利点洒水栓地面标高（m），h14。',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: false,
  },
  {
    field: 'reuseWaterTankStopPumpWaterLevel',
    label: '停泵水位',
    helpMessage: '回用水池（箱）或回用井停泵水位，h15。',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: false,
  },
  {
    field: 'reusePumpOutflowHead',
    label: '流出水头',
    helpMessage: '最不利点洒水栓流出水头h16（m），推荐取2~3。',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: false,
  },
  {
    field: 'reusePumpLift',
    label: '回用泵扬程',
    helpMessage: '回用泵扬程H3（m）。',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: true,
  },
  {
    label: '◆ 回用泵组计算',
    field: 'divider53',
    component: 'Divider',
    colProps: { span: 23 },
  },
  {
    field: 'ultravioletDisinfection',
    label: '消毒设备规模',
    helpMessage: '紫外线消毒设备流量Q6（m3/h）',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: false,
  },
  {
    field: 'reuseWaterTankModel',
    label: '回用水池、回用泵组及消毒设备选型',
    dynamicDisabled: true,
    colProps: { span: EQUIP.WIDTH_TEXT_AREA },
    component: 'InputTextArea',
    labelWidth: EQUIP.WIDTH_LABEL_WIDTH,
  },
  {
    label: '污水抽升泵井及泵组选型',
    field: 'divider80',
    component: 'Divider',
  },
  {
    label: '◆ 污水抽升泵井计算',
    field: 'divider81',
    component: 'Divider',
    colProps: { span: 23 },
  },
  {
    field: 'pumpWellSize',
    label: '泵井直径',
    helpMessage: [
      '分圆形、矩形。',
      '圆形井采用院通用图“肆水（2017）7411”；',
      '矩形井采用国标图集08S305',
    ],
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: false,
  },
  {
    field: 'pumpingWellSewageVolume',
    label: '泵井有效容积',
    helpMessage: '按地铁设计规范，单泵15~20min储水量',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: true,
  },
  {
    field: 'pumpWellWaterDepth',
    label: '泵井有效水深',
    helpMessage: '污水抽升泵井有效水深（m）',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: true,
  },
  {
    field: 'pumpWellWaterPipeElevation',
    label: '进水管底标高',
    helpMessage: '污水抽升泵井进水管底绝对标高（m）',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: false,
  },
  {
    field: 'pumpWellStopPumpWaterLevel',
    label: '停泵水位',
    helpMessage: '开泵水位在进水管底以下0.2m',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: true,
  },
  {
    field: 'swpDesignGroundElevationPumpWell',
    label: '泵井设计地面标高',
    helpMessage: '抽升泵井设计地面标高h2（m）。',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: false,
  },
  {
    field: 'swpStopPumpWaterLevelInnerHeight',
    label: '停泵水位距内底高',
    helpMessage: '按水泵参数选取，需加上水泵基础高度,基础高度圆形井为0.3m，矩形井为0.1m ，h8',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: false,
  },
  {
    field: 'swpconcreteThickness',
    label: '调节井封底混凝土厚度h9（m）',
    helpMessage: '',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    show: false,
    dynamicDisabled: false,
  },
  {
    field: 'swpLiftWellHeight',
    label: '泵井高度',
    helpMessage:
      '圆形井：污水调节泵井深度H1（m），院通用图“肆水（2017）7411”。按H1≥h2+0.3-h5+h8+h9计。矩形井：污水调节泵井深度H1（m），国标图“08S305”。按H1≥h2-h5+h8计。',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: false,
  },
  {
    label: '◆ 潜污泵组计算',
    field: 'divider82',
    component: 'Divider',
    colProps: { span: 23 },
  },
  {
    field: 'pumpingWellSewageMeasure',
    label: '抽升井污水量(m3/d）',
    helpMessage: '',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: false,
  },
  {
    field: 'submersibleSewagePumpFlow',
    label: '潜污泵流量',
    helpMessage: '变化系数参《室外排水设计标准》表4.1.15',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: false,
  },
  {
    field: 'pumpWellTotalHeadLoss',
    label: '总水头损失',
    helpMessage: '',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER_JS },
    dynamicDisabled: false,
  },
  {
    field: 'js5',
    component: 'Input',
    label: '',
    colProps: { span: 1 },
    slot: 'add5',
  },
  {
    field: 'pumpWellDesignGround',
    label: '设计地面标高',
    helpMessage: '',
    show: false,
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: false,
  },
  {
    field: 'liftingPipeHighestPoint',
    label: '最不利点标高',
    helpMessage: '压力管终点地面标高或扬水管最高点处绝对标高（m）',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: false,
  },
  {
    field: 'spwOutflowHead',
    label: '流出水头（m）',
    helpMessage: '',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: false,
  },
  {
    field: 'spwPumpLift',
    label: '潜污泵扬程（m）',
    helpMessage: '',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: true,
  },
  {
    field: 'spwPumpModel',
    label: '污水抽升泵井及泵组选型',
    dynamicDisabled: true,
    colProps: { span: EQUIP.WIDTH_TEXT_AREA },
    component: 'InputTextArea',
    labelWidth: EQUIP.WIDTH_LABEL_WIDTH,
  },

  {
    label: '含油污水处理（调沉池+气浮过滤）设备选型',
    field: 'divider9',
    component: 'Divider',
  },
  {
    label: '◆ 调沉池计算',
    field: 'divider91',
    component: 'Divider',
    colProps: { span: 23 },
  },
  {
    field: 'amountOilyWastewater',
    label: '处理污水量',
    helpMessage: '需处理的含油污水量(m3/d）',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: false,
  },
  {
    field: 'workTime',
    label: '设备工作小时',
    helpMessage: '设备工作时数（h），推荐按两班14h计。',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: false,
  },
  {
    field: 'settlingTankStopTime',
    label: '调沉停留时间',
    helpMessage: 't建议取2~4h',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: false,
  },
  {
    field: 'settlingTankVolume',
    label: '调沉池容积',
    helpMessage: '调沉池计算容积（m3），按V≥W*t/T计。',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: true,
  },
  {
    label: '◆ 气浮过滤设备计算',
    field: 'divider92',
    component: 'Divider',
    colProps: { span: 23 },
  },
  {
    field: 'iaffDeviceSpecs',
    label: '设备处理能力',
    helpMessage: '所需一体化气浮过滤设备处理能力Q1（m3/h），按Q1≥W/T计。',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: true,
  },

  {
    field: 'inletSubmersibleSewagePumpFlow',
    label: '潜污泵流量',
    helpMessage: '进水潜污泵（调沉池内）流量Q2（m3/h）',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: true,
  },
  {
    field: 'iaffTotalHeadLoss',
    label: '总水头损失',
    helpMessage: '',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER_JS },
    dynamicDisabled: false,
  },
  {
    field: 'js6',
    component: 'Input',
    label: '',
    colProps: { span: 1 },
    slot: 'add6',
  },
  {
    field: 'iaffWaterPipeElevation',
    label: '设备进水管标高',
    helpMessage: '气浮过滤设备进水管标高（m）',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: false,
  },
  {
    field: 'iaffWaterInletPressure',
    label: '设备进水压力',
    helpMessage: '气浮过滤设备进水压力（m水头），默认为5m。',
    defaultValue: 5,
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: false,
  },
  {
    field: 'iaffStopPumpWaterLevel',
    label: '停泵水位',
    helpMessage: '潜污泵可设在调沉池内',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: false,
  },
  {
    field: 'iaffExcessHead',
    label: '富裕水头',
    helpMessage: '处理设备进水管流出水头h6（m），推荐取2~3。',
    defaultValue: 2,
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: false,
  },
  {
    field: 'spwInletPumpLift',
    label: '潜污泵扬程',
    helpMessage: '进水潜污泵扬程（m）',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: false,
  },
  {
    field: 'sedimentationIAFFModel',
    label: '调沉池及气浮过滤设备选型',
    dynamicDisabled: true,
    colProps: { span: EQUIP.WIDTH_TEXT_AREA },
    component: 'InputTextArea',
    labelWidth: EQUIP.WIDTH_LABEL_WIDTH,
  },
  {
    label: '厌氧滤池+人工湿地选型',
    field: 'divider100',
    component: 'Divider',
  },
  {
    field: 'liftSewageTreatmentCapacity',
    label: '处理污水量',
    helpMessage: '需处理的污水量(m3/d）',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: false,
  },
  {
    field: 'anaerobicFilter',
    label: '厌氧滤池处理能力',
    helpMessage: '需厌氧滤池达到的处理能力Q1(m3/d）',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: false,
  },
  {
    field: 'constructedWetland',
    label: '人工湿地处理能力',
    helpMessage: '需人工湿地达到的处理能力Q2(m3/d）',
    component: 'InputNumberExpand1',
    colProps: { span: EQUIP.WIDTH_NUMBER },
    dynamicDisabled: true,
  },
  {
    field: 'liftWaterPointModel',
    label: '厌氧滤池及人工湿地选型',
    dynamicDisabled: true,
    colProps: { span: EQUIP.WIDTH_TEXT_AREA },
    component: 'InputTextArea',
    labelWidth: EQUIP.WIDTH_LABEL_WIDTH,
  },
];
