export const chonseTypeEquip = (e, updateSchema) => {
  let ifShowObj = {
    divider10: false,
    sewageTreatmentCapacity: false,
    sbrDeviceWork: false,
    sbrCycleWorkTime: false,
    sbrDeviceSpecs: false,
    sbrModel: false,

    divider20: false,
    divider21: false,
    sewageRegulatingWellVolume: false,
    adjustWellDiameter: false,
    adjustWellWaterDepth: false,
    adjustWellWaterPipeElevation: false,
    adjustWellStopPumpWaterLevel: false,
    divider22: false,
    adjustWellPumpFlow: false,
    sbrDeviceInletPipeElevation: false,
    adjustWellTotalHeadLoss: false,
    js1: false,
    sewageTreatmentOutflowHead: false,
    adjustWellPumpLift: false,
    adjustPumpModel: false,
    sbrDesignGroundElevationPumpWell: false,
    sbrstopPumpWaterLevelInnerHeight: false,
    adjustWellDepth: false,

    divider30: false,
    filterSpecs: false,

    divider60: false,
    mbrsewageTreatmentCapacity: false,
    mbrDeviceSpecs: false,
    mbrModel: false,

    divider70: false,
    divider71: false,
    adjustTime: false,
    mbrsewageRegulatingWellVolume: false,
    mbradjustWellDiameter: false,
    mbradjustWellWaterDepth: false,
    mbradjustWellWaterPipeElevation: false,
    mbradjustWellStopPumpWaterLevel: false,
    divider72: false,
    mbradjustWellPumpFlow: false,
    mbrDeviceInletPipeElevation: false,
    mbrTotalHeadLoss: false,
    js4: false,
    mbrDeviceOutflowHead: false,
    mbrPumpLift: false,
    adjustWellModel: false,
    mbrdesignGroundElevationPumpWell: false,
    mbrstopPumpWaterLevelInnerHeight: false,
    mbrliftWellHeight: false,

    divider40: false,
    divider41: false,
    pumpingWellDiameter: false,
    sewageStopTime: false,
    pumpingWellVolume: false,
    pumpingWellWaterDepth: false,
    pumpingWellWaterPipeElevation: false,
    pumpingWellStopPumpWaterLevel: false,
    divider42: false,
    pumpingWellPumpFlow: false,
    filterWaterInletPressure: false,
    pumpingWellTotalHeadLoss: false,
    js2: false,
    filterWaterInletElevation: false,
    sewageExcessHead: false,
    pumpingWellPumpLift: false,
    pumpingWellModel: false,
    pwdesignGroundElevationPumpWell: false,
    pwstopPumpWaterLevelInnerHeight: false,
    pwliftWellHeight: false,
    divider50: false,
    divider51: false,
    reuseWaterTankVolume: false,
    divider52: false,
    sprinklerFlowRate: false,
    makeGreenSprinklingWater: false,
    reusePumpFlow: false,
    makeGreenTotalHeadLoss: false,
    js3: false,
    sprinklerWorkPressure: false,
    dullSprinklerGroundLevel: false,
    reuseWaterTankStopPumpWaterLevel: false,
    reusePumpOutflowHead: false,
    reusePumpLift: false,
    divider53: false,
    ultravioletDisinfection: false,
    reuseWaterTankModel: false,

    divider80: false,
    divider81: false,
    pumpWellSize: false,
    pumpingWellSewageVolume: false,
    pumpWellWaterDepth: false,
    pumpWellWaterPipeElevation: false,
    pumpWellStopPumpWaterLevel: false,
    divider82: false,
    pumpingWellSewageMeasure: false,
    submersibleSewagePumpFlow: false,
    pumpWellTotalHeadLoss: false,
    js5: false,
    pumpWellDesignGround: false,
    liftingPipeHighestPoint: false,
    spwOutflowHead: false,
    spwPumpLift: false,
    spwpumpModel: false,
    swpdesignGroundElevationPumpWell: false,
    swpstopPumpWaterLevelInnerHeight: false,
    swpliftWellHeight: false,

    divider9: false,
    divider91: false,
    amountOilyWastewater: false,
    workTime: false,
    settlingTankStopTime: false,
    settlingTankVolume: false,
    divider92: false,
    iaffDeviceSpecs: false,
    inletSubmersibleSewagePumpFlow: false,
    iaffTotalHeadLoss: false,
    js6: false,
    iaffWaterPipeElevation: false,
    iaffWaterInletPressure: false,
    iaffStopPumpWaterLevel: false,
    iaffExcessHead: false,
    spwInletPumpLift: false,
    sedimentationIAFFModel: false,

    divider100: false,
    liftSewageTreatmentCapacity: false,
    anaerobicFilter: false,
    constructedWetland: false,
    liftWaterPointModel: false,
  };
  if (e === 'GreenReuseSBR') {
    //1 2 3 4 5
    ifShowObj = {
      divider10: true,
      sewageTreatmentCapacity: true,
      sbrDeviceWork: true,
      sbrCycleWorkTime: true,
      sbrDeviceSpecs: true,
      sbrModel: true,

      divider20: true,
      divider21: true,
      sewageRegulatingWellVolume: true,
      adjustWellDiameter: true,
      adjustWellWaterDepth: true,
      adjustWellWaterPipeElevation: true,
      adjustWellStopPumpWaterLevel: true,
      divider22: true,
      adjustWellPumpFlow: true,
      sbrDeviceInletPipeElevation: true,
      adjustWellTotalHeadLoss: true,
      js1: true,
      sewageTreatmentOutflowHead: true,
      adjustWellPumpLift: true,
      adjustPumpModel: true,
      sbrDesignGroundElevationPumpWell: true,
      sbrstopPumpWaterLevelInnerHeight: true,
      adjustWellDepth: true,
      divider30: true,
      filterSpecs: true,

      divider60: false,
      mbrsewageTreatmentCapacity: false,
      mbrDeviceSpecs: false,
      mbrModel: false,
      divider70: false,
      divider71: false,
      adjustTime: false,
      mbrsewageRegulatingWellVolume: false,
      mbradjustWellDiameter: false,
      mbradjustWellWaterDepth: false,
      mbradjustWellWaterPipeElevation: false,
      mbradjustWellStopPumpWaterLevel: false,

      divider72: false,
      mbradjustWellPumpFlow: false,
      mbrDeviceInletPipeElevation: false,
      mbrTotalHeadLoss: false,
      js4: false,
      mbrDeviceOutflowHead: false,
      mbrPumpLift: false,
      adjustWellModel: false,
      mbrdesignGroundElevationPumpWell: false,
      mbrstopPumpWaterLevelInnerHeight: false,
      mbrliftWellHeight: false,
      divider40: true,
      divider41: true,
      pumpingWellDiameter: true,
      sewageStopTime: true,
      pumpingWellVolume: true,
      pumpingWellWaterDepth: true,
      pumpingWellWaterPipeElevation: true,
      pumpingWellStopPumpWaterLevel: true,
      divider42: true,
      pumpingWellPumpFlow: true,
      filterWaterInletPressure: true,
      pumpingWellTotalHeadLoss: true,
      js2: true,
      filterWaterInletElevation: true,
      sewageExcessHead: true,
      pumpingWellPumpLift: true,
      pumpingWellModel: true,
      pwdesignGroundElevationPumpWell: true,
      pwstopPumpWaterLevelInnerHeight: true,
      pwliftWellHeight: true,

      divider50: true,
      divider51: true,
      reuseWaterTankVolume: true,
      divider52: true,
      sprinklerFlowRate: true,
      makeGreenSprinklingWater: true,
      reusePumpFlow: true,
      makeGreenTotalHeadLoss: true,
      js3: true,
      sprinklerWorkPressure: true,
      dullSprinklerGroundLevel: true,
      reuseWaterTankStopPumpWaterLevel: true,
      reusePumpOutflowHead: true,
      reusePumpLift: true,
      divider53: true,
      ultravioletDisinfection: true,
      reuseWaterTankModel: true,

      divider80: false,
      divider81: false,
      pumpWellSize: false,
      pumpingWellSewageVolume: false,
      pumpWellWaterDepth: false,
      pumpWellWaterPipeElevation: false,
      pumpWellStopPumpWaterLevel: false,
      divider82: false,
      pumpingWellSewageMeasure: false,
      submersibleSewagePumpFlow: false,
      pumpWellTotalHeadLoss: false,
      js5: false,
      pumpWellDesignGround: false,
      liftingPipeHighestPoint: false,
      spwOutflowHead: false,
      spwPumpLift: false,
      spwpumpModel: false,
      swpdesignGroundElevationPumpWell: false,
      swpstopPumpWaterLevelInnerHeight: false,
      swpliftWellHeight: false,

      divider9: false,
      divider91: false,
      amountOilyWastewater: false,
      workTime: false,
      settlingTankStopTime: false,
      settlingTankVolume: false,
      divider92: false,
      iaffDeviceSpecs: false,
      inletSubmersibleSewagePumpFlow: false,
      iaffTotalHeadLoss: false,
      js6: false,
      iaffWaterPipeElevation: false,
      iaffWaterInletPressure: false,
      iaffStopPumpWaterLevel: false,
      iaffExcessHead: false,
      spwInletPumpLift: false,
      sedimentationIAFFModel: false,

      divider100: false,
      liftSewageTreatmentCapacity: false,
      anaerobicFilter: false,
      constructedWetland: false,
      liftWaterPointModel: false,
    };
  } else if (e === 'GreenReuseMBR') {
    //6 7 4 5
    ifShowObj = {
      divider10: false,
      sewageTreatmentCapacity: false,
      sbrDeviceWork: false,
      sbrCycleWorkTime: false,
      sbrDeviceSpecs: false,
      sbrModel: false,
      divider20: false,
      divider21: false,
      sewageRegulatingWellVolume: false,
      adjustWellDiameter: false,
      adjustWellWaterDepth: false,
      adjustWellWaterPipeElevation: false,
      adjustWellStopPumpWaterLevel: false,
      divider22: false,
      adjustWellPumpFlow: false,
      sbrDeviceInletPipeElevation: false,
      adjustWellTotalHeadLoss: false,
      js1: false,
      sewageTreatmentOutflowHead: false,
      adjustWellPumpLift: false,
      adjustPumpModel: false,
      sbrDesignGroundElevationPumpWell: false,
      sbrstopPumpWaterLevelInnerHeight: false,
      adjustWellDepth: false,
      divider30: false,
      filterSpecs: false,

      divider60: true,
      mbrsewageTreatmentCapacity: true,
      mbrDeviceSpecs: true,
      mbrModel: true,
      divider70: true,
      divider71: true,
      adjustTime: true,
      mbrsewageRegulatingWellVolume: true,
      mbradjustWellDiameter: true,
      mbradjustWellWaterDepth: true,
      mbradjustWellWaterPipeElevation: true,
      mbradjustWellStopPumpWaterLevel: true,

      divider72: true,
      mbradjustWellPumpFlow: true,
      mbrDeviceInletPipeElevation: true,
      mbrTotalHeadLoss: true,
      js4: true,
      mbrDeviceOutflowHead: true,
      mbrPumpLift: true,
      adjustWellModel: true,
      mbrdesignGroundElevationPumpWell: true,
      mbrstopPumpWaterLevelInnerHeight: true,
      mbrliftWellHeight: true,

      divider40: true,
      divider41: true,
      pumpingWellDiameter: true,
      sewageStopTime: true,
      pumpingWellVolume: true,
      pumpingWellWaterDepth: true,
      pumpingWellWaterPipeElevation: true,
      pumpingWellStopPumpWaterLevel: true,
      divider42: true,
      pumpingWellPumpFlow: true,
      filterWaterInletPressure: true,
      pumpingWellTotalHeadLoss: true,
      js2: true,
      filterWaterInletElevation: true,
      sewageExcessHead: true,
      pumpingWellPumpLift: true,
      pumpingWellModel: true,
      pwdesignGroundElevationPumpWell: true,
      pwstopPumpWaterLevelInnerHeight: true,
      pwliftWellHeight: true,

      divider50: true,
      divider51: true,
      reuseWaterTankVolume: true,
      divider52: true,
      sprinklerFlowRate: true,
      makeGreenSprinklingWater: true,
      reusePumpFlow: true,
      makeGreenTotalHeadLoss: true,
      js3: true,
      sprinklerWorkPressure: true,
      dullSprinklerGroundLevel: true,
      reuseWaterTankStopPumpWaterLevel: true,
      reusePumpOutflowHead: true,
      reusePumpLift: true,
      divider53: true,
      ultravioletDisinfection: true,
      reuseWaterTankModel: true,

      divider80: false,
      divider81: false,
      pumpWellSize: false,
      pumpingWellSewageVolume: false,
      pumpWellWaterDepth: false,
      pumpWellWaterPipeElevation: false,
      pumpWellStopPumpWaterLevel: false,
      divider82: false,
      pumpingWellSewageMeasure: false,
      submersibleSewagePumpFlow: false,
      pumpWellTotalHeadLoss: false,
      js5: false,
      pumpWellDesignGround: false,
      liftingPipeHighestPoint: false,
      spwOutflowHead: false,
      spwPumpLift: false,
      spwpumpModel: false,
      swpdesignGroundElevationPumpWell: false,
      swpstopPumpWaterLevelInnerHeight: false,
      swpliftWellHeight: false,

      divider9: false,
      divider91: false,
      amountOilyWastewater: false,
      workTime: false,
      settlingTankStopTime: false,
      settlingTankVolume: false,
      divider92: false,
      iaffDeviceSpecs: false,
      inletSubmersibleSewagePumpFlow: false,
      iaffTotalHeadLoss: false,
      js6: false,
      iaffWaterPipeElevation: false,
      iaffWaterInletPressure: false,
      iaffStopPumpWaterLevel: false,
      iaffExcessHead: false,
      spwInletPumpLift: false,
      sedimentationIAFFModel: false,

      divider100: false,
      liftSewageTreatmentCapacity: false,
      anaerobicFilter: false,
      constructedWetland: false,
      liftWaterPointModel: false,
    };
  } else if (e === 'NearbyDischargeSBR') {
    //1 2 3 4
    ifShowObj = {
      divider10: true,
      sewageTreatmentCapacity: true,
      sbrDeviceWork: true,
      sbrCycleWorkTime: true,
      sbrDeviceSpecs: true,
      sbrModel: true,
      divider20: true,
      divider21: true,
      sewageRegulatingWellVolume: true,
      adjustWellDiameter: true,
      adjustWellWaterDepth: true,
      adjustWellWaterPipeElevation: true,
      adjustWellStopPumpWaterLevel: true,
      divider22: true,
      adjustWellPumpFlow: true,
      sbrDeviceInletPipeElevation: true,
      adjustWellTotalHeadLoss: true,
      js1: true,
      sewageTreatmentOutflowHead: true,
      adjustWellPumpLift: true,
      adjustPumpModel: true,
      sbrDesignGroundElevationPumpWell: true,
      sbrstopPumpWaterLevelInnerHeight: true,
      adjustWellDepth: true,
      divider30: true,
      filterSpecs: true,

      divider60: false,
      mbrsewageTreatmentCapacity: false,
      mbrDeviceSpecs: false,
      mbrModel: false,
      divider70: false,
      divider71: false,
      adjustTime: false,
      mbrsewageRegulatingWellVolume: false,
      mbradjustWellDiameter: false,
      mbradjustWellWaterDepth: false,
      mbradjustWellWaterPipeElevation: false,
      mbradjustWellStopPumpWaterLevel: false,

      divider72: false,
      mbradjustWellPumpFlow: false,
      mbrDeviceInletPipeElevation: false,
      mbrTotalHeadLoss: false,
      js4: false,
      mbrDeviceOutflowHead: false,
      mbrPumpLift: false,
      adjustWellModel: false,
      mbrdesignGroundElevationPumpWell: false,
      mbrstopPumpWaterLevelInnerHeight: false,
      mbrliftWellHeight: false,

      divider40: true,
      divider41: true,
      pumpingWellDiameter: true,
      sewageStopTime: true,
      pumpingWellVolume: true,
      pumpingWellWaterDepth: true,
      pumpingWellWaterPipeElevation: true,
      pumpingWellStopPumpWaterLevel: true,
      divider42: true,
      pumpingWellPumpFlow: true,
      filterWaterInletPressure: true,
      pumpingWellTotalHeadLoss: true,
      js2: true,
      filterWaterInletElevation: true,
      sewageExcessHead: true,
      pumpingWellPumpLift: true,
      pumpingWellModel: true,
      pwdesignGroundElevationPumpWell: true,
      pwstopPumpWaterLevelInnerHeight: true,
      pwliftWellHeight: true,

      divider50: false,
      divider51: false,
      reuseWaterTankVolume: false,
      divider52: false,
      sprinklerFlowRate: false,
      makeGreenSprinklingWater: false,
      reusePumpFlow: false,
      makeGreenTotalHeadLoss: false,
      js3: false,
      sprinklerWorkPressure: false,
      dullSprinklerGroundLevel: false,
      reuseWaterTankStopPumpWaterLevel: false,
      reusePumpOutflowHead: false,
      reusePumpLift: false,
      divider53: false,
      ultravioletDisinfection: false,
      reuseWaterTankModel: false,

      divider80: false,
      divider81: false,
      pumpWellSize: false,
      pumpingWellSewageVolume: false,
      pumpWellWaterDepth: false,
      pumpWellWaterPipeElevation: false,
      pumpWellStopPumpWaterLevel: false,
      divider82: false,
      pumpingWellSewageMeasure: false,
      submersibleSewagePumpFlow: false,
      pumpWellTotalHeadLoss: false,
      js5: false,
      pumpWellDesignGround: false,
      liftingPipeHighestPoint: false,
      spwOutflowHead: false,
      spwPumpLift: false,
      spwpumpModel: false,
      swpdesignGroundElevationPumpWell: false,
      swpstopPumpWaterLevelInnerHeight: false,
      swpliftWellHeight: false,

      divider9: false,
      divider91: false,
      amountOilyWastewater: false,
      workTime: false,
      settlingTankStopTime: false,
      settlingTankVolume: false,
      divider92: false,
      iaffDeviceSpecs: false,
      inletSubmersibleSewagePumpFlow: false,
      iaffTotalHeadLoss: false,
      js6: false,
      iaffWaterPipeElevation: false,
      iaffWaterInletPressure: false,
      iaffStopPumpWaterLevel: false,
      iaffExcessHead: false,
      spwInletPumpLift: false,
      sedimentationIAFFModel: false,

      divider100: false,
      liftSewageTreatmentCapacity: false,
      anaerobicFilter: false,
      constructedWetland: false,
      liftWaterPointModel: false,
    };
  } else if (e === 'NearbyDischargeMBR') {
    // 6 7 4
    ifShowObj = {
      divider10: false,
      sewageTreatmentCapacity: false,
      sbrDeviceWork: false,
      sbrCycleWorkTime: false,
      sbrDeviceSpecs: false,
      sbrModel: false,
      divider20: false,
      divider21: false,
      sewageRegulatingWellVolume: false,
      adjustWellDiameter: false,
      adjustWellWaterDepth: false,
      adjustWellWaterPipeElevation: false,
      adjustWellStopPumpWaterLevel: false,
      divider22: false,
      adjustWellPumpFlow: false,
      sbrDeviceInletPipeElevation: false,
      adjustWellTotalHeadLoss: false,
      js1: false,
      sewageTreatmentOutflowHead: false,
      adjustWellPumpLift: false,
      adjustPumpModel: false,
      sbrDesignGroundElevationPumpWell: false,
      sbrstopPumpWaterLevelInnerHeight: false,
      adjustWellDepth: false,
      divider30: false,
      filterSpecs: false,

      divider60: true,
      mbrsewageTreatmentCapacity: true,
      mbrDeviceSpecs: true,
      mbrModel: true,
      divider70: true,
      divider71: true,
      adjustTime: true,
      mbrsewageRegulatingWellVolume: true,
      mbradjustWellDiameter: true,
      mbradjustWellWaterDepth: true,
      mbradjustWellWaterPipeElevation: true,
      mbradjustWellStopPumpWaterLevel: true,

      divider72: true,
      mbradjustWellPumpFlow: true,
      mbrDeviceInletPipeElevation: true,
      mbrTotalHeadLoss: true,
      js4: true,
      mbrDeviceOutflowHead: true,
      mbrPumpLift: true,
      adjustWellModel: true,
      mbrdesignGroundElevationPumpWell: true,
      mbrstopPumpWaterLevelInnerHeight: true,
      mbrliftWellHeight: true,

      divider40: true,
      divider41: true,
      pumpingWellDiameter: true,
      sewageStopTime: true,
      pumpingWellVolume: true,
      pumpingWellWaterDepth: true,
      pumpingWellWaterPipeElevation: true,
      pumpingWellStopPumpWaterLevel: true,
      divider42: true,
      pumpingWellPumpFlow: true,
      filterWaterInletPressure: true,
      pumpingWellTotalHeadLoss: true,
      js2: true,
      filterWaterInletElevation: true,
      sewageExcessHead: true,
      pumpingWellPumpLift: true,
      pumpingWellModel: true,
      pwdesignGroundElevationPumpWell: true,
      pwstopPumpWaterLevelInnerHeight: true,
      pwliftWellHeight: true,

      divider50: false,
      divider51: false,
      reuseWaterTankVolume: false,
      divider52: false,
      sprinklerFlowRate: false,
      makeGreenSprinklingWater: false,
      reusePumpFlow: false,
      makeGreenTotalHeadLoss: false,
      js3: false,
      sprinklerWorkPressure: false,
      dullSprinklerGroundLevel: false,
      reuseWaterTankStopPumpWaterLevel: false,
      reusePumpOutflowHead: false,
      reusePumpLift: false,
      divider53: false,
      ultravioletDisinfection: false,
      reuseWaterTankModel: false,

      divider80: false,
      divider81: false,
      pumpWellSize: false,
      pumpingWellSewageVolume: false,
      pumpWellWaterDepth: false,
      pumpWellWaterPipeElevation: false,
      pumpWellStopPumpWaterLevel: false,
      divider82: false,
      pumpingWellSewageMeasure: false,
      submersibleSewagePumpFlow: false,
      pumpWellTotalHeadLoss: false,
      js5: false,
      pumpWellDesignGround: false,
      liftingPipeHighestPoint: false,
      spwOutflowHead: false,
      spwPumpLift: false,
      spwpumpModel: false,
      swpdesignGroundElevationPumpWell: false,
      swpstopPumpWaterLevelInnerHeight: false,
      swpliftWellHeight: false,

      divider9: false,
      divider91: false,
      amountOilyWastewater: false,
      workTime: false,
      settlingTankStopTime: false,
      settlingTankVolume: false,
      divider92: false,
      iaffDeviceSpecs: false,
      inletSubmersibleSewagePumpFlow: false,
      iaffTotalHeadLoss: false,
      js6: false,
      iaffWaterPipeElevation: false,
      iaffWaterInletPressure: false,
      iaffStopPumpWaterLevel: false,
      iaffExcessHead: false,
      spwInletPumpLift: false,
      sedimentationIAFFModel: false,

      divider100: false,
      liftSewageTreatmentCapacity: false,
      anaerobicFilter: false,
      constructedWetland: false,
      liftWaterPointModel: false,
    };
  } else if (e === 'ConstructedWetlands') {
    // 10
    ifShowObj = {
      divider10: false,
      sewageTreatmentCapacity: false,
      sbrDeviceWork: false,
      sbrCycleWorkTime: false,
      sbrDeviceSpecs: false,
      sbrModel: false,

      divider20: false,
      divider21: false,
      sewageRegulatingWellVolume: false,
      adjustWellDiameter: false,
      adjustWellWaterDepth: false,
      adjustWellWaterPipeElevation: false,
      adjustWellStopPumpWaterLevel: false,
      divider22: false,
      adjustWellPumpFlow: false,
      sbrDeviceInletPipeElevation: false,
      adjustWellTotalHeadLoss: false,
      js1: false,
      sewageTreatmentOutflowHead: false,
      adjustWellPumpLift: false,
      adjustPumpModel: false,
      sbrDesignGroundElevationPumpWell: false,
      sbrstopPumpWaterLevelInnerHeight: false,
      adjustWellDepth: false,

      divider30: false,
      filterSpecs: false,

      divider60: false,
      mbrsewageTreatmentCapacity: false,
      mbrDeviceSpecs: false,
      mbrModel: false,

      divider70: false,
      divider71: false,
      adjustTime: false,
      mbrsewageRegulatingWellVolume: false,
      mbradjustWellDiameter: false,
      mbradjustWellWaterDepth: false,
      mbradjustWellWaterPipeElevation: false,
      mbradjustWellStopPumpWaterLevel: false,
      divider72: false,
      mbradjustWellPumpFlow: false,
      mbrDeviceInletPipeElevation: false,
      mbrTotalHeadLoss: false,
      js4: false,
      mbrDeviceOutflowHead: false,
      mbrPumpLift: false,
      adjustWellModel: false,
      mbrdesignGroundElevationPumpWell: false,
      mbrstopPumpWaterLevelInnerHeight: false,
      mbrliftWellHeight: false,

      divider40: false,
      divider41: false,
      pumpingWellDiameter: false,
      sewageStopTime: false,
      pumpingWellVolume: false,
      pumpingWellWaterDepth: false,
      pumpingWellWaterPipeElevation: false,
      pumpingWellStopPumpWaterLevel: false,
      divider42: false,
      pumpingWellPumpFlow: false,
      filterWaterInletPressure: false,
      pumpingWellTotalHeadLoss: false,
      js2: false,
      filterWaterInletElevation: false,
      sewageExcessHead: false,
      pumpingWellPumpLift: false,
      pumpingWellModel: false,
      pwdesignGroundElevationPumpWell: false,
      pwstopPumpWaterLevelInnerHeight: false,
      pwliftWellHeight: false,
      divider50: false,
      divider51: false,
      reuseWaterTankVolume: false,
      divider52: false,
      sprinklerFlowRate: false,
      makeGreenSprinklingWater: false,
      reusePumpFlow: false,
      makeGreenTotalHeadLoss: false,
      js3: false,
      sprinklerWorkPressure: false,
      dullSprinklerGroundLevel: false,
      reuseWaterTankStopPumpWaterLevel: false,
      reusePumpOutflowHead: false,
      reusePumpLift: false,
      divider53: false,
      ultravioletDisinfection: false,
      reuseWaterTankModel: false,

      divider80: false,
      divider81: false,
      pumpWellSize: false,
      pumpingWellSewageVolume: false,
      pumpWellWaterDepth: false,
      pumpWellWaterPipeElevation: false,
      pumpWellStopPumpWaterLevel: false,
      divider82: false,
      pumpingWellSewageMeasure: false,
      submersibleSewagePumpFlow: false,
      pumpWellTotalHeadLoss: false,
      js5: false,
      pumpWellDesignGround: false,
      liftingPipeHighestPoint: false,
      spwOutflowHead: false,
      spwPumpLift: false,
      spwpumpModel: false,
      swpdesignGroundElevationPumpWell: false,
      swpstopPumpWaterLevelInnerHeight: false,
      swpliftWellHeight: false,

      divider9: false,
      divider91: false,
      amountOilyWastewater: false,
      workTime: false,
      settlingTankStopTime: false,
      settlingTankVolume: false,
      divider92: false,
      iaffDeviceSpecs: false,
      inletSubmersibleSewagePumpFlow: false,
      iaffTotalHeadLoss: false,
      js6: false,
      iaffWaterPipeElevation: false,
      iaffWaterInletPressure: false,
      iaffStopPumpWaterLevel: false,
      iaffExcessHead: false,
      spwInletPumpLift: false,
      sedimentationIAFFModel: false,

      divider100: true,
      liftSewageTreatmentCapacity: true,
      anaerobicFilter: true,
      constructedWetland: true,
      liftWaterPointModel: true,
    };
  } else if (e === 'AFE') {
    // 9
    ifShowObj = {
      divider10: false,
      sewageTreatmentCapacity: false,
      sbrDeviceWork: false,
      sbrCycleWorkTime: false,
      sbrDeviceSpecs: false,
      sbrModel: false,

      divider20: false,
      divider21: false,
      sewageRegulatingWellVolume: false,
      adjustWellDiameter: false,
      adjustWellWaterDepth: false,
      adjustWellWaterPipeElevation: false,
      adjustWellStopPumpWaterLevel: false,
      divider22: false,
      adjustWellPumpFlow: false,
      sbrDeviceInletPipeElevation: false,
      adjustWellTotalHeadLoss: false,
      js1: false,
      sewageTreatmentOutflowHead: false,
      adjustWellPumpLift: false,
      adjustPumpModel: false,
      sbrDesignGroundElevationPumpWell: false,
      sbrstopPumpWaterLevelInnerHeight: false,
      adjustWellDepth: false,

      divider30: false,
      filterSpecs: false,

      divider60: false,
      mbrsewageTreatmentCapacity: false,
      mbrDeviceSpecs: false,
      mbrModel: false,

      divider70: false,
      divider71: false,
      adjustTime: false,
      mbrsewageRegulatingWellVolume: false,
      mbradjustWellDiameter: false,
      mbradjustWellWaterDepth: false,
      mbradjustWellWaterPipeElevation: false,
      mbradjustWellStopPumpWaterLevel: false,
      divider72: false,
      mbradjustWellPumpFlow: false,
      mbrDeviceInletPipeElevation: false,
      mbrTotalHeadLoss: false,
      js4: false,
      mbrDeviceOutflowHead: false,
      mbrPumpLift: false,
      adjustWellModel: false,
      mbrdesignGroundElevationPumpWell: false,
      mbrstopPumpWaterLevelInnerHeight: false,
      mbrliftWellHeight: false,

      divider40: false,
      divider41: false,
      pumpingWellDiameter: false,
      sewageStopTime: false,
      pumpingWellVolume: false,
      pumpingWellWaterDepth: false,
      pumpingWellWaterPipeElevation: false,
      pumpingWellStopPumpWaterLevel: false,
      divider42: false,
      pumpingWellPumpFlow: false,
      filterWaterInletPressure: false,
      pumpingWellTotalHeadLoss: false,
      js2: false,
      filterWaterInletElevation: false,
      sewageExcessHead: false,
      pumpingWellPumpLift: false,
      pumpingWellModel: false,
      pwdesignGroundElevationPumpWell: false,
      pwstopPumpWaterLevelInnerHeight: false,
      pwliftWellHeight: false,
      divider50: false,
      divider51: false,
      reuseWaterTankVolume: false,
      divider52: false,
      sprinklerFlowRate: false,
      makeGreenSprinklingWater: false,
      reusePumpFlow: false,
      makeGreenTotalHeadLoss: false,
      js3: false,
      sprinklerWorkPressure: false,
      dullSprinklerGroundLevel: false,
      reuseWaterTankStopPumpWaterLevel: false,
      reusePumpOutflowHead: false,
      reusePumpLift: false,
      divider53: false,
      ultravioletDisinfection: false,
      reuseWaterTankModel: false,

      divider80: false,
      divider81: false,
      pumpWellSize: false,
      pumpingWellSewageVolume: false,
      pumpWellWaterDepth: false,
      pumpWellWaterPipeElevation: false,
      pumpWellStopPumpWaterLevel: false,
      divider82: false,
      pumpingWellSewageMeasure: false,
      submersibleSewagePumpFlow: false,
      pumpWellTotalHeadLoss: false,
      js5: false,
      pumpWellDesignGround: false,
      liftingPipeHighestPoint: false,
      spwOutflowHead: false,
      spwPumpLift: false,
      spwpumpModel: false,
      swpdesignGroundElevationPumpWell: false,
      swpstopPumpWaterLevelInnerHeight: false,
      swpliftWellHeight: false,

      divider9: true,
      divider91: true,
      amountOilyWastewater: true,
      workTime: true,
      settlingTankStopTime: true,
      settlingTankVolume: true,
      divider92: true,
      iaffDeviceSpecs: true,
      inletSubmersibleSewagePumpFlow: true,
      iaffTotalHeadLoss: true,
      js6: true,
      iaffWaterPipeElevation: true,
      iaffWaterInletPressure: true,
      iaffStopPumpWaterLevel: true,
      iaffExcessHead: true,
      spwInletPumpLift: true,
      sedimentationIAFFModel: true,

      divider100: false,
      liftSewageTreatmentCapacity: false,
      anaerobicFilter: false,
      constructedWetland: false,
      liftWaterPointModel: false,
    };
  } else if (e === 'ExtractionDirectDischarge') {
    // 8
    ifShowObj = {
      divider10: false,
      sewageTreatmentCapacity: false,
      sbrDeviceWork: false,
      sbrCycleWorkTime: false,
      sbrDeviceSpecs: false,
      sbrModel: false,

      divider20: false,
      divider21: false,
      sewageRegulatingWellVolume: false,
      adjustWellDiameter: false,
      adjustWellWaterDepth: false,
      adjustWellWaterPipeElevation: false,
      adjustWellStopPumpWaterLevel: false,
      divider22: false,
      adjustWellPumpFlow: false,
      sbrDeviceInletPipeElevation: false,
      adjustWellTotalHeadLoss: false,
      js1: false,
      sewageTreatmentOutflowHead: false,
      adjustWellPumpLift: false,
      adjustPumpModel: false,
      sbrDesignGroundElevationPumpWell: false,
      sbrstopPumpWaterLevelInnerHeight: false,
      adjustWellDepth: false,

      divider30: false,
      filterSpecs: false,

      divider60: false,
      mbrsewageTreatmentCapacity: false,
      mbrDeviceSpecs: false,
      mbrModel: false,

      divider70: false,
      divider71: false,
      adjustTime: false,
      mbrsewageRegulatingWellVolume: false,
      mbradjustWellDiameter: false,
      mbradjustWellWaterDepth: false,
      mbradjustWellWaterPipeElevation: false,
      mbradjustWellStopPumpWaterLevel: false,
      divider72: false,
      mbradjustWellPumpFlow: false,
      mbrDeviceInletPipeElevation: false,
      mbrTotalHeadLoss: false,
      js4: false,
      mbrDeviceOutflowHead: false,
      mbrPumpLift: false,
      adjustWellModel: false,
      mbrdesignGroundElevationPumpWell: false,
      mbrstopPumpWaterLevelInnerHeight: false,
      mbrliftWellHeight: false,

      divider40: false,
      divider41: false,
      pumpingWellDiameter: false,
      sewageStopTime: false,
      pumpingWellVolume: false,
      pumpingWellWaterDepth: false,
      pumpingWellWaterPipeElevation: false,
      pumpingWellStopPumpWaterLevel: false,
      divider42: false,
      pumpingWellPumpFlow: false,
      filterWaterInletPressure: false,
      pumpingWellTotalHeadLoss: false,
      js2: false,
      filterWaterInletElevation: false,
      sewageExcessHead: false,
      pumpingWellPumpLift: false,
      pumpingWellModel: false,
      pwdesignGroundElevationPumpWell: false,
      pwstopPumpWaterLevelInnerHeight: false,
      pwliftWellHeight: false,
      divider50: false,
      divider51: false,
      reuseWaterTankVolume: false,
      divider52: false,
      sprinklerFlowRate: false,
      makeGreenSprinklingWater: false,
      reusePumpFlow: false,
      makeGreenTotalHeadLoss: false,
      js3: false,
      sprinklerWorkPressure: false,
      dullSprinklerGroundLevel: false,
      reuseWaterTankStopPumpWaterLevel: false,
      reusePumpOutflowHead: false,
      reusePumpLift: false,
      divider53: false,
      ultravioletDisinfection: false,
      reuseWaterTankModel: false,

      divider80: true,
      divider81: true,
      pumpWellSize: true,
      pumpingWellSewageVolume: true,
      pumpWellWaterDepth: true,
      pumpWellWaterPipeElevation: true,
      pumpWellStopPumpWaterLevel: true,
      divider82: true,
      pumpingWellSewageMeasure: true,
      submersibleSewagePumpFlow: true,
      pumpWellTotalHeadLoss: true,
      js5: true,
      pumpWellDesignGround: true,
      liftingPipeHighestPoint: true,
      spwOutflowHead: true,
      spwPumpLift: true,
      spwpumpModel: true,
      swpdesignGroundElevationPumpWell: true,
      swpstopPumpWaterLevelInnerHeight: true,
      swpliftWellHeight: true,

      divider9: false,
      divider91: false,
      amountOilyWastewater: false,
      workTime: false,
      settlingTankStopTime: false,
      settlingTankVolume: false,
      divider92: false,
      iaffDeviceSpecs: false,
      inletSubmersibleSewagePumpFlow: false,
      iaffTotalHeadLoss: false,
      js6: false,
      iaffWaterPipeElevation: false,
      iaffWaterInletPressure: false,
      iaffStopPumpWaterLevel: false,
      iaffExcessHead: false,
      spwInletPumpLift: false,
      sedimentationIAFFModel: false,

      divider100: false,
      liftSewageTreatmentCapacity: false,
      anaerobicFilter: false,
      constructedWetland: false,
      liftWaterPointModel: false,
    };
  }
  updateSchema([
    {
      field: 'divider10',
      show: ifShowObj.divider10,
    },
    {
      field: 'sewageTreatmentCapacity',
      show: ifShowObj.sewageTreatmentCapacity,
      required: ifShowObj.sewageTreatmentCapacity,
    },
    {
      field: 'sbrDeviceWork',
      show: ifShowObj.sbrDeviceWork,
      required: ifShowObj.sbrDeviceWork,
    },
    {
      field: 'sbrCycleWorkTime',
      show: ifShowObj.sbrCycleWorkTime,
      required: ifShowObj.sbrCycleWorkTime,
    },
    {
      field: 'sbrDeviceSpecs',
      show: ifShowObj.sbrDeviceSpecs,
    },
    {
      field: 'sbrModel',
      show: ifShowObj.sbrModel,
    },
    {
      field: 'divider20',
      show: ifShowObj.divider20,
    },
    {
      field: 'divider21',
      show: ifShowObj.divider21,
    },
    {
      field: 'sewageRegulatingWellVolume',
      show: ifShowObj.sewageRegulatingWellVolume,
    },
    {
      field: 'adjustWellDiameter',
      show: ifShowObj.adjustWellDiameter,
      required: ifShowObj.adjustWellDiameter,
    },
    {
      field: 'adjustWellWaterDepth',
      show: ifShowObj.adjustWellWaterDepth,
    },
    {
      field: 'adjustWellWaterPipeElevation',
      show: ifShowObj.adjustWellWaterPipeElevation,
      required: ifShowObj.adjustWellWaterPipeElevation,
    },
    {
      field: 'adjustWellStopPumpWaterLevel',
      show: ifShowObj.adjustWellStopPumpWaterLevel,
    },
    {
      field: 'divider22',
      show: ifShowObj.divider22,
    },
    {
      field: 'adjustWellPumpFlow',
      show: ifShowObj.adjustWellPumpFlow,
    },
    {
      field: 'sbrDeviceInletPipeElevation',
      show: ifShowObj.sbrDeviceInletPipeElevation,
      required: ifShowObj.sbrDeviceInletPipeElevation,
    },
    {
      field: 'adjustWellTotalHeadLoss',
      show: ifShowObj.adjustWellTotalHeadLoss,
      required: ifShowObj.adjustWellTotalHeadLoss,
    },
    {
      field: 'sbrDesignGroundElevationPumpWell',
      show: ifShowObj.sbrDesignGroundElevationPumpWell,
      required: ifShowObj.sbrDesignGroundElevationPumpWell,
    },
    {
      field: 'sbrstopPumpWaterLevelInnerHeight',
      show: ifShowObj.sbrstopPumpWaterLevelInnerHeight,
      required: ifShowObj.sbrstopPumpWaterLevelInnerHeight,
    },
    {
      field: 'adjustWellDepth',
      show: ifShowObj.adjustWellDepth,
    },
    {
      field: 'js1',
      show: ifShowObj.js1,
    },
    {
      field: 'sewageTreatmentOutflowHead',
      show: ifShowObj.sewageTreatmentOutflowHead,
      required: ifShowObj.sewageTreatmentOutflowHead,
    },
    {
      field: 'adjustWellPumpLift',
      show: ifShowObj.adjustWellPumpLift,
    },
    {
      field: 'adjustPumpModel',
      show: ifShowObj.adjustPumpModel,
    },
    {
      field: 'divider30',
      show: ifShowObj.divider30,
    },
    {
      field: 'filterSpecs',
      show: ifShowObj.filterSpecs,
    },
    {
      field: 'divider60',
      show: ifShowObj.divider60,
    },
    {
      field: 'mbrsewageTreatmentCapacity',
      show: ifShowObj.mbrsewageTreatmentCapacity,
      required: ifShowObj.mbrsewageTreatmentCapacity,
    },
    {
      field: 'mbrDeviceSpecs',
      show: ifShowObj.mbrDeviceSpecs,
    },
    {
      field: 'mbrModel',
      show: ifShowObj.mbrModel,
    },
    {
      field: 'divider70',
      show: ifShowObj.divider70,
    },
    {
      field: 'divider71',
      show: ifShowObj.divider71,
    },
    {
      field: 'adjustTime',
      show: ifShowObj.adjustTime,
      required: ifShowObj.adjustTime,
    },
    {
      field: 'mbrsewageRegulatingWellVolume',
      show: ifShowObj.mbrsewageRegulatingWellVolume,
    },
    {
      field: 'mbradjustWellDiameter',
      show: ifShowObj.mbradjustWellDiameter,
      required: ifShowObj.mbradjustWellDiameter,
    },
    {
      field: 'mbradjustWellWaterDepth',
      show: ifShowObj.mbradjustWellWaterDepth,
    },
    {
      field: 'mbradjustWellWaterPipeElevation',
      show: ifShowObj.mbradjustWellWaterPipeElevation,
      required: ifShowObj.mbradjustWellWaterPipeElevation,
    },
    {
      field: 'mbradjustWellStopPumpWaterLevel',
      show: ifShowObj.mbradjustWellStopPumpWaterLevel,
    },
    {
      field: 'divider72',
      show: ifShowObj.divider72,
    },
    {
      field: 'mbradjustWellPumpFlow',
      show: ifShowObj.mbradjustWellPumpFlow,
    },
    {
      field: 'mbrDeviceInletPipeElevation',
      show: ifShowObj.mbrDeviceInletPipeElevation,
      required: ifShowObj.mbrDeviceInletPipeElevation,
    },
    {
      field: 'mbrTotalHeadLoss',
      show: ifShowObj.mbrTotalHeadLoss,
      required: ifShowObj.mbrTotalHeadLoss,
    },
    {
      field: 'js4',
      show: ifShowObj.js4,
    },
    {
      field: 'mbrDeviceOutflowHead',
      show: ifShowObj.mbrDeviceOutflowHead,
      required: ifShowObj.mbrDeviceOutflowHead,
    },
    {
      field: 'mbrPumpLift',
      show: ifShowObj.mbrPumpLift,
    },
    {
      field: 'adjustWellModel',
      show: ifShowObj.adjustWellModel,
    },
    {
      field: 'mbrdesignGroundElevationPumpWell',
      show: ifShowObj.mbrdesignGroundElevationPumpWell,
      required: ifShowObj.mbrdesignGroundElevationPumpWell,
    },
    {
      field: 'mbrstopPumpWaterLevelInnerHeight',
      show: ifShowObj.mbrstopPumpWaterLevelInnerHeight,
      required: ifShowObj.mbrstopPumpWaterLevelInnerHeight,
    },
    {
      field: 'mbrliftWellHeight',
      show: ifShowObj.mbrliftWellHeight,
    },
    {
      field: 'divider40',
      show: ifShowObj.divider40,
    },
    {
      field: 'divider41',
      show: ifShowObj.divider41,
    },
    {
      field: 'pumpingWellDiameter',
      show: ifShowObj.pumpingWellDiameter,
      required: ifShowObj.pumpingWellDiameter,
    },
    {
      field: 'sewageStopTime',
      show: ifShowObj.sewageStopTime,
      required: ifShowObj.sewageStopTime,
    },
    {
      field: 'pumpingWellVolume',
      show: ifShowObj.pumpingWellVolume,
    },
    {
      field: 'pumpingWellWaterDepth',
      show: ifShowObj.pumpingWellWaterDepth,
    },
    {
      field: 'pumpingWellWaterPipeElevation',
      show: ifShowObj.pumpingWellWaterPipeElevation,
      required: ifShowObj.pumpingWellWaterPipeElevation,
    },
    {
      field: 'pumpingWellStopPumpWaterLevel',
      show: ifShowObj.pumpingWellStopPumpWaterLevel,
    },
    {
      field: 'divider42',
      show: ifShowObj.divider42,
    },
    {
      field: 'pumpingWellPumpFlow',
      show: ifShowObj.pumpingWellPumpFlow,
    },
    {
      field: 'filterWaterInletPressure',
      show: ifShowObj.filterWaterInletPressure,
      required: ifShowObj.filterWaterInletPressure,
    },
    {
      field: 'pumpingWellTotalHeadLoss',
      show: ifShowObj.pumpingWellTotalHeadLoss,
      required: ifShowObj.pumpingWellTotalHeadLoss,
    },
    {
      field: 'js2',
      show: ifShowObj.js2,
    },
    {
      field: 'filterWaterInletElevation',
      show: ifShowObj.filterWaterInletElevation,
      required: ifShowObj.filterWaterInletElevation,
    },
    {
      field: 'sewageExcessHead',
      show: ifShowObj.sewageExcessHead,
      required: ifShowObj.sewageExcessHead,
    },
    {
      field: 'pumpingWellPumpLift',
      show: ifShowObj.pumpingWellPumpLift,
    },
    {
      field: 'pumpingWellModel',
      show: ifShowObj.pumpingWellModel,
    },
    {
      field: 'pwdesignGroundElevationPumpWell',
      show: ifShowObj.pwdesignGroundElevationPumpWell,
      required: ifShowObj.pwdesignGroundElevationPumpWell,
    },
    {
      field: 'pwstopPumpWaterLevelInnerHeight',
      show: ifShowObj.pwstopPumpWaterLevelInnerHeight,
      required: ifShowObj.pwstopPumpWaterLevelInnerHeight,
    },
    {
      field: 'pwliftWellHeight',
      show: ifShowObj.pwliftWellHeight,
    },
    {
      field: 'divider50',
      show: ifShowObj.divider50,
    },
    {
      field: 'divider51',
      show: ifShowObj.divider51,
    },
    {
      field: 'reuseWaterTankVolume',
      show: ifShowObj.reuseWaterTankVolume,
    },
    {
      field: 'divider52',
      show: ifShowObj.divider52,
    },
    {
      field: 'sprinklerFlowRate',
      show: ifShowObj.sprinklerFlowRate,
      required: ifShowObj.sprinklerFlowRate,
    },
    {
      field: 'makeGreenSprinklingWater',
      show: ifShowObj.makeGreenSprinklingWater,
      required: ifShowObj.makeGreenSprinklingWater,
    },
    {
      field: 'reusePumpFlow',
      show: ifShowObj.reusePumpFlow,
    },
    {
      field: 'makeGreenTotalHeadLoss',
      show: ifShowObj.makeGreenTotalHeadLoss,
      required: ifShowObj.makeGreenTotalHeadLoss,
    },
    {
      field: 'js3',
      show: ifShowObj.js3,
    },
    {
      field: 'sprinklerWorkPressure',
      show: ifShowObj.sprinklerWorkPressure,
      required: ifShowObj.sprinklerWorkPressure,
    },
    {
      field: 'dullSprinklerGroundLevel',
      show: ifShowObj.dullSprinklerGroundLevel,
      required: ifShowObj.dullSprinklerGroundLevel,
    },
    {
      field: 'reuseWaterTankStopPumpWaterLevel',
      show: ifShowObj.reuseWaterTankStopPumpWaterLevel,
      required: ifShowObj.reuseWaterTankStopPumpWaterLevel,
    },
    {
      field: 'reusePumpOutflowHead',
      show: ifShowObj.reusePumpOutflowHead,
      required: ifShowObj.reusePumpOutflowHead,
    },
    {
      field: 'reusePumpLift',
      show: ifShowObj.reusePumpLift,
    },
    {
      field: 'divider53',
      show: ifShowObj.divider53,
    },
    {
      field: 'ultravioletDisinfection',
      show: ifShowObj.ultravioletDisinfection,
      required: ifShowObj.ultravioletDisinfection,
    },
    {
      field: 'reuseWaterTankModel',
      show: ifShowObj.reuseWaterTankModel,
    },
    {
      field: 'divider80',
      show: ifShowObj.divider80,
    },
    {
      field: 'divider81',
      show: ifShowObj.divider81,
    },
    {
      field: 'pumpWellSize',
      show: ifShowObj.pumpWellSize,
      required: ifShowObj.pumpWellSize,
    },
    {
      field: 'pumpingWellSewageVolume',
      show: ifShowObj.pumpingWellSewageVolume,
    },
    {
      field: 'pumpWellWaterDepth',
      show: ifShowObj.pumpWellWaterDepth,
    },
    {
      field: 'pumpWellWaterPipeElevation',
      show: ifShowObj.pumpWellWaterPipeElevation,
      required: ifShowObj.pumpWellWaterPipeElevation,
    },
    {
      field: 'pumpWellStopPumpWaterLevel',
      show: ifShowObj.pumpWellStopPumpWaterLevel,
    },
    {
      field: 'divider82',
      show: ifShowObj.divider82,
    },
    {
      field: 'pumpingWellSewageMeasure',
      show: ifShowObj.pumpingWellSewageMeasure,
      required: ifShowObj.pumpingWellSewageMeasure,
    },
    {
      field: 'submersibleSewagePumpFlow',
      show: ifShowObj.submersibleSewagePumpFlow,
      required: ifShowObj.submersibleSewagePumpFlow,
    },
    {
      field: 'pumpWellTotalHeadLoss',
      show: ifShowObj.pumpWellTotalHeadLoss,
      required: ifShowObj.pumpWellTotalHeadLoss,
    },
    {
      field: 'swpdesignGroundElevationPumpWell',
      show: ifShowObj.swpdesignGroundElevationPumpWell,
      required: ifShowObj.swpdesignGroundElevationPumpWell,
    },
    {
      field: 'swpstopPumpWaterLevelInnerHeight',
      show: ifShowObj.swpstopPumpWaterLevelInnerHeight,
      required: ifShowObj.swpstopPumpWaterLevelInnerHeight,
    },
    {
      field: 'swpliftWellHeight',
      show: ifShowObj.swpliftWellHeight,
    },
    {
      field: 'js5',
      show: ifShowObj.js5,
    },
    {
      field: 'liftingPipeHighestPoint',
      show: ifShowObj.liftingPipeHighestPoint,
      required: ifShowObj.liftingPipeHighestPoint,
    },
    {
      field: 'spwOutflowHead',
      show: ifShowObj.spwOutflowHead,
      required: ifShowObj.spwOutflowHead,
    },
    {
      field: 'spwPumpLift',
      show: ifShowObj.spwPumpLift,
    },
    {
      field: 'spwpumpModel',
      show: ifShowObj.spwpumpModel,
    },
    {
      field: 'divider9',
      show: ifShowObj.divider9,
    },
    {
      field: 'divider9',
      show: ifShowObj.divider9,
    },
    {
      field: 'divider91',
      show: ifShowObj.divider91,
    },
    {
      field: 'amountOilyWastewater',
      show: ifShowObj.amountOilyWastewater,
      required: ifShowObj.amountOilyWastewater,
    },
    {
      field: 'workTime',
      show: ifShowObj.workTime,
      required: ifShowObj.workTime,
    },
    {
      field: 'settlingTankStopTime',
      show: ifShowObj.settlingTankStopTime,
      required: ifShowObj.settlingTankStopTime,
    },
    {
      field: 'settlingTankVolume',
      show: ifShowObj.settlingTankVolume,
    },
    {
      field: 'divider92',
      show: ifShowObj.divider92,
    },
    {
      field: 'iaffDeviceSpecs',
      show: ifShowObj.iaffDeviceSpecs,
    },
    {
      field: 'inletSubmersibleSewagePumpFlow',
      show: ifShowObj.inletSubmersibleSewagePumpFlow,
    },
    {
      field: 'iaffTotalHeadLoss',
      show: ifShowObj.iaffTotalHeadLoss,
      required: ifShowObj.iaffTotalHeadLoss,
    },
    {
      field: 'js6',
      show: ifShowObj.js6,
    },
    {
      field: 'iaffStopPumpWaterLevel',
      show: ifShowObj.iaffStopPumpWaterLevel,
      required: ifShowObj.iaffStopPumpWaterLevel,
    },
    {
      field: 'iaffExcessHead',
      show: ifShowObj.iaffExcessHead,
      required: ifShowObj.iaffExcessHead,
    },
    {
      field: 'spwInletPumpLift',
      show: ifShowObj.spwInletPumpLift,
    },
    {
      field: 'sedimentationIAFFModel',
      show: ifShowObj.sedimentationIAFFModel,
    },
    {
      field: 'iaffWaterInletPressure',
      show: ifShowObj.iaffWaterInletPressure,
      required: ifShowObj.iaffWaterInletPressure,
    },
    {
      field: 'iaffWaterPipeElevation',
      show: ifShowObj.iaffWaterPipeElevation,
      required: ifShowObj.iaffWaterPipeElevation,
    },
    {
      field: 'divider100',
      show: ifShowObj.divider100,
    },
    {
      field: 'liftSewageTreatmentCapacity',
      show: ifShowObj.liftSewageTreatmentCapacity,
      required: ifShowObj.liftSewageTreatmentCapacity,
    },
    {
      field: 'liftSewageTreatmentCapacity',
      show: ifShowObj.liftSewageTreatmentCapacity,
      required: ifShowObj.liftSewageTreatmentCapacity,
    },
    {
      field: 'anaerobicFilter',
      show: ifShowObj.anaerobicFilter,
      required: ifShowObj.anaerobicFilter,
    },
    {
      field: 'constructedWetland',
      show: ifShowObj.constructedWetland,
    },
    {
      field: 'liftWaterPointModel',
      show: ifShowObj.liftWaterPointModel,
    },
  ]);
};
