export const pageInfo = {
  list: [
    {
      id: 1001,
      station: '北京',
      station_type: 4,
      max_consumption_water: 1000,
      max_displacement_water: 2000,
    },
    {
      id: 1002,
      station: '石家庄',
      station_type: 2,
      max_consumption_water: 1000,
      max_displacement_water: 2000,
    },
    {
      id: 1003,
      station: '郑州',
      station_type: 1,
      max_consumption_water: 1000,
      max_displacement_water: 2000,
    },
    {
      id: 1004,
      station: '孝感',
      station_type: 3,
      max_consumption_water: 1000,
      max_displacement_water: 2000,
    },
    {
      id: 1005,
      station: '武汉',
      station_type: 1,
      max_consumption_water: 1000,
      max_displacement_water: 2000,
    },
  ],
  split: {
    size: 10,
    page: 1,
    total: 5,
  },
};

export const beijingRecord = {
  id: 1001,
  station: '北京',
  station_type: 1,
  traveler_use_list: [
    {
      use_name: '通过旅客列车',
      unit: '对',
      daily_water_recent: 8,
      daily_water_forward: 7,
      amount_recent: 100,
      amount_forward: 101,
      unit_water: 10,
      unit_water_level: 9,
    },
    {
      use_name: '始发终到旅客列车',
      unit: '对',
      daily_water_recent: 8,
      daily_water_forward: 7,
      amount_recent: 100,
      amount_forward: 101,
      unit_water: 10,
      unit_water_level: 9,
    },
  ],
  traveler_recent_total: 200,
  product_use_list: [
    {
      use_name: '客机这番话段',
      unit: '对',
      daily_water_recent: 8,
      daily_water_forward: 7,
      amount_recent: 100,
      amount_forward: 101,
      unit_water: 10,
      unit_water_level: 9,
    },
    {
      use_name: '整备运转办公楼',
      unit: '对',
      daily_water_recent: 8,
      daily_water_forward: 7,
      amount_recent: 100,
      amount_forward: 101,
      unit_water: 10,
      unit_water_1: 9,
    },
    {
      use_name: '冷却水制备及油脂发放间',
      unit: '对',
      daily_water_recent: 8,
      daily_water_forward: 7,
      amount_recent: 100,
      amount_forward: 101,
      unit_water: 10,
      unit_water_1: 9,
    },
  ],
  product_recent_total: 200,
};
